apiVersion: v1
kind: Service
metadata:
  name: bord
spec:
  type: ClusterIP
  selector:
    apiVersion: v1
kind: Service
metadata:
  name: bord-service
spec:
  type: NodePort          # exposes on all cluster nodes
  selector:
    apiVersion: v1
kind: Service
metadata:
  name: bord-service
spec:
  type: NodePort          # exposes on all cluster nodes
  selector:
    core.spinkube.dev/app-name: bord  # note the underscore instead of slash
  ports:
    - protocol: TCP
      port: 80           # port your app listens on internally
      targetPort: 80     # container port
